### PR TITLE
More hardware support

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Review by athoik — COMMENTED** [review]
Why strstr(buf,"Meson-64") required?

The strstr(buf,"Meson-6") doesn't cover that case already?

**Comment by persianpros** [comment]
We have two wetekplay(Meson-6) and wetekplay2(Meson-64), It won't hurt if we could just cover two of them in one line ;)

Merge this if you found it helpful otherwise close it ...

**Comment by athoik** [comment]
> The strstr(buf,"Meson-6") doesn't cover that case already?

**Comment by persianpros** [comment]
Nope

**Comment by athoik** [comment]
```
#include <stdio.h>
#include <string.h>

int main()
{
        const char* buf = "Meson-64";
        printf("strstr = %s\n", strstr(buf, "Meson-6") ? "YES" : "NO");
        return 0;
}
```

Is it a YES or NO?

**Comment by persianpros** [comment]
I get your point and you're right, If you have access to edit please remove https://github.com/OpenPLi/aio-grab/pull/10/commits/3f9e1f18e99d3d0b06f32485d3ffa6dd3ee6a9a5 otherwise it won't harm if you merge it :)

**Comment by athoik** [comment]
Anyway... I add them here https://github.com/OpenPLi/aio-grab/pull/11

**Pull request closed without merging**
